name: CI

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  lint:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        node: [ 18.x, 20.x ]
    name: lint
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: install dependencies
        run: npm install
      - name: check lint
        run: npm run lint
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - run: npm ci

      - run: npm test

  keys_api_check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18.x, 20.x]

    needs: [lint, tests]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - run: npm ci

      - run: npm run test:response

  release:
    name: Semantic release
    runs-on: 'ubuntu-latest'
    needs: [lint, tests]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: install dependencies
        run: npm ci
      - name: release
        run: npx semantic-release
        env:
          GH_TOKEN:  ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          HUSKY: 0
