name: "Keys check"

on:
  schedule:
    - cron: "30 1 1,15 * *"


jobs:
  keys_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - run: npm ci

      - run: npm run test:keys
